version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=oracle+oracledb://rm553764:fiap24@oracle.fiap.com.br:1521/?sid=ord&mode=thin
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000
